services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backnet
      - frontnet
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    networks:
      - backnet
      - frontnet

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontnet

networks:
  backnet:
    driver: bridge
  frontnet:
     driver: bridge

