services:
  beam-dev:
    image: python:3.8-slim
    volumes:
      - ./beam:/app # Adjust the volume to where your Beam scripts are located
    working_dir: /app
    command: bash -c "pip install apache-beam[gcp] && python your_beam_script.py" # Install Apache Beam and run your script
    networks:
      - backnet

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backnet
      - frontnet
  
  redis:
    image: redis:latest
    hostname: redis
    networks:
      - backnet
      - frontnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
    networks:
      - backnet
      - frontnet

networks:
  backnet:
    driver: bridge
  frontnet:
    driver: bridge
