services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backnet
      - frontnet
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
    networks:
      - backnet
      - frontnet

  worker:
    build:
      context: ./backend
      dockerfile: ./scripts/Dockerfile
    volumes:
      - ./backend:/app
    links:
      - rabbitmq
    environment:
        - CELERY_BROKER=pyamqp://rabbitmq:5672//
    networks:
      - backnet
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - frontnet

networks:
  backnet:
    driver: bridge
  frontnet:
     driver: bridge


