openapi: "4.0.0"
info:
  version: 0.1.0
  title: Video Analyzer
paths:
  /upload-video:
    post:
      summary: Upload a video to be analyzed
      operationId: uploadVideo
      tags:
        - videos
      requestBody:
        content:
          video/mp4:
            schema:
              type: string
              format: binary
        required: true
      responses:
        '201':
          description: Video successfully uploaded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Video"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /frames/{videoId}:
    get:
      summary: The frames chosen from a specific video
      operationId: framesChosenFromVideo
      tags:
        - frames
      parameters:
        - name: videoId
          in: path
          required: true
          description: The id of the video to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Frames"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /results/{videoId}:
    get:
      summary: The results from analyzing a specific video
      operationId: resultsFromVideo
      tags:
        - results
      parameters:
        - name: videoId
          in: path
          required: true
          description: The id of the video analyzed
          schema:
            type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalysisResult"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Video:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
    Frame:
      type: object
      required:
        - frameNum
      properties:
        frameNum:
          type: integer
          format: int64
    Frames:
      type: array
      items:
        $ref: "#/components/schemas/Frame"
    AnalysisResult:
      type: object
      required:
        - objectsDetected
      properties:
        objectsDetected:
          type: array
          items:
            $ref: "#/components/schemas/DetectedObject"
    DetectedObject:
      type: object
      required:
        - objectName
        - confidenceLevel
      properties:
        objectName:
          type: string
        confidenceLevel:
          type: number
          format: float
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
