version: '3' 
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'    
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network
  consumer:
    build: consumer
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network
  publisher:
    build: publisher
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network
networks:
  network: {backnet}