# implementing CI/CD pipeline for backend
name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: DB
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Needed to keep the container running until tests are done
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      working-directory: ./backend
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip libsm6 libxext6 python3-opencv
        sudo apt-get install -y --no-install-recommends ffmpeg
        pip install -r requirements.txt

    - name: Lint with Ruff
      working-directory: ./backend
      run: |
        pip install ruff
        ruff check .
      continue-on-error: true
    - name: Test with pytest
      working-directory: ./backend
      run: |
        pytest
    # Add deployment steps
